# Generated by Django 3.0.7 on 2020-06-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_date']},
        ),
    ]
